Repository heyverse/hey, pull requests merged in 2022-08, with the labels that each got.

#198 fix: retain logged in session
  src/components/SiteLayout.tsx
Labels: bug

#354 fix: remove unwanted deps in `useEffect`
  src/components/Publication/Actions/Collect/index.tsx
  src/components/Publication/Actions/Like.tsx
  src/components/Publication/Actions/Mirror.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Shared/IFramely/index.tsx
Labels: 🐛 bug, 💅 enhancement

#370 feat: lens api updates
  src/components/Comment/NewComment/index.tsx
  src/components/Community/Create.tsx
  src/components/Crowdfund/Create.tsx
  src/components/Publication/NewPost/index.tsx
  src/components/Settings/Profile/Profile.tsx
  src/generated/types.ts
  src/pages/api/upload.ts
Labels: 💅 enhancement, ✨ feature

#467 fix: don't persist currentUser 🙅
  src/components/Comment/Feed.tsx
  src/components/Comment/New.tsx
  src/components/Community/Details.tsx
  src/components/Community/New.tsx
  src/components/Crowdfund/New.tsx
  src/components/Explore/Feed.tsx
  src/components/Home/Feed.tsx
  src/components/Home/RecommendedProfiles.tsx
  src/components/Home/SetDefaultProfile.tsx
  src/components/Home/SetProfile.tsx
  src/components/Home/index.tsx
  src/components/Notification/Icon.tsx
  src/components/Notification/List.tsx
  src/components/Notification/Type/FollowerNotification.tsx
  src/components/Profile/Details.tsx
  src/components/Profile/Feed.tsx
  src/components/Profile/New.tsx
  src/components/Profile/index.tsx
  src/components/Publication/Actions/Like.tsx
  src/components/Publication/Actions/Menu/index.tsx
  src/components/Publication/Actions/Mirror.tsx
  src/components/Publication/New/index.tsx
  src/components/Publication/index.tsx
  src/components/Report/index.tsx
  src/components/Search/Publications.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Account/Verification.tsx
  src/components/Settings/Account/index.tsx
  src/components/Settings/Allowance/index.tsx
  src/components/Settings/Data/index.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Dispatcher/ToggleDispatcher.tsx
  src/components/Settings/Dispatcher/index.tsx
  src/components/Settings/Profile/NFTPicture.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Settings/Profile/index.tsx
  src/components/Settings/Sidebar.tsx
  src/components/Shared/Follow.tsx
  src/components/Shared/Navbar/Login/WalletSelector.tsx
  src/components/Shared/Navbar/MenuItems.tsx
  src/components/Shared/Navbar/MoreNavItems.tsx
  src/components/Shared/Navbar/index.tsx
  src/components/Shared/SelectCollectModule/FeeEntry.tsx
  src/components/Shared/SuperFollow/FollowModule.tsx
  src/components/SiteLayout.tsx
  src/store/app.ts
Labels: 💅 enhancement

#481 chore: reduce bundle size
  src/components/Layout.tsx
  src/pages/Providers.tsx
  src/pages/_app.tsx
Labels: 💅 enhancement

#483 refactor: useEffect in layout
  src/components/Layout.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Shared/Navbar/SignedUser.tsx
  src/components/Shared/Navbar/UnsignedUser.tsx
Labels: 🐛 bug

#515 refactor: onCompleted and onError
  src/components/Comment/New.tsx
  src/components/Community/Join.tsx
  src/components/Community/New.tsx
  src/components/Community/Settings/index.tsx
  src/components/Crowdfund/New.tsx
  src/components/Publication/Actions/Collect/CollectModule.tsx
  src/components/Publication/Actions/Like.tsx
  src/components/Publication/Actions/Menu/Delete.tsx
  src/components/Publication/Actions/Mirror.tsx
  src/components/Publication/Crowdfund/Fund.tsx
  src/components/Publication/New/index.tsx
  src/components/Report/index.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Allowance/Button.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Dispatcher/ToggleDispatcher.tsx
  src/components/Settings/Profile/NFTPicture.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Shared/Follow.tsx
  src/components/Shared/Navbar/Login/WalletSelector.tsx
  src/components/Shared/SuperFollow/FollowModule.tsx
  src/components/Shared/Unfollow.tsx
  src/components/utils/hooks/useBroadcast.tsx
  src/lib/mixpanel.ts
  src/lib/onError.ts
Labels: 💅 enhancement

#519 chore: use <Mutation> type in useMutation
  src/components/Comment/New.tsx
  src/components/Community/Join.tsx
  src/components/Community/New.tsx
  src/components/Community/Settings/index.tsx
  src/components/Crowdfund/New.tsx
  src/components/Publication/Actions/Collect/CollectModule.tsx
  src/components/Publication/Actions/Like.tsx
  src/components/Publication/Actions/Menu/Delete.tsx
  src/components/Publication/Actions/Mirror.tsx
  src/components/Publication/Crowdfund/Fund.tsx
  src/components/Publication/New/index.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Dispatcher/ToggleDispatcher.tsx
  src/components/Settings/Profile/NFTPicture.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Shared/Follow.tsx
  src/components/Shared/SuperFollow/FollowModule.tsx
  src/components/Shared/Unfollow.tsx
Labels: 💅 enhancement

#521 fix: auth blink
  src/components/Layout.tsx
Labels: 🐛 bug

#526 chore: remove gitpod
  .gitpod.yml
  README.md
  script/commands.txt
  script/gp-welcome
  src/components/Pages/Thanks.tsx
Labels: dependencies

#528 chore: reduce usage of `any`
  data/hashflags.ts
  src/components/Publication/Type/CommunityPost.tsx
  src/components/Settings/Allowance/Allowance.tsx
  src/components/Shared/IFramely/Embed.tsx
  src/components/Shared/IFramely/Player.tsx
  src/generated/lenstertypes.ts
Labels: 💅 enhancement

#535 fix: mutual followers
  src/components/Profile/MutualFollowers/index.tsx
Labels: 🐛 bug

#544 fix: remove unused isAuthenticated state
  src/components/Comment/New.tsx
  src/components/Community/Join.tsx
  src/components/Community/New.tsx
  src/components/Crowdfund/New.tsx
  src/components/Home/index.tsx
  src/components/Layout.tsx
  src/components/Notification/index.tsx
  src/components/Publication/Actions/Like.tsx
  src/components/Publication/Actions/Mirror.tsx
  src/components/Publication/New/index.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Profile/NFTPicture.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Shared/Navbar/Login/WalletSelector.tsx
  src/components/Shared/Navbar/SignedUser.tsx
  src/components/Shared/Navbar/index.tsx
  src/components/Shared/SuperFollow/FollowModule.tsx
  src/components/Shared/Unfollow.tsx
  src/store/app.ts
Labels: 🐛 bug

#549 chore: fix comma in README.md
  README.md
Labels: 📙 documentation

#559 chore: use newNextLinkBehavior
  next.config.js
  src/components/Home/SetDefaultProfile.tsx
  src/components/Home/SetProfile.tsx
  src/components/Notification/Icon.tsx
  src/components/Notification/Profile.tsx
  src/components/Notification/Type/CollectNotification/Content.tsx
  src/components/Notification/Type/CollectNotification/index.tsx
  src/components/Notification/Type/CommentNotification.tsx
  src/components/Notification/Type/MentionNotification.tsx
  src/components/Notification/Type/MirrorNotification.tsx
  src/components/Profile/Details.tsx
  src/components/Publication/Actions/index.tsx
  src/components/Publication/Crowdfund/index.tsx
  src/components/Publication/OnchainMeta.tsx
  src/components/Publication/SinglePublication.tsx
  src/components/Publication/ThreadBody.tsx
  src/components/Publication/Type/Collected.tsx
  src/components/Publication/Type/CommentedPublication.tsx
  src/components/Publication/Type/Mirrored.tsx
  src/components/Search/Sidebar.tsx
  src/components/Settings/Account/CrossPost.tsx
  src/components/Settings/Sidebar.tsx
  src/components/Shared/Attachments.tsx
  src/components/Shared/Footer.tsx
  src/components/Shared/IFramely/Embed.tsx
  src/components/Shared/Markup.tsx
  src/components/Shared/Navbar/MenuItems.tsx
  src/components/Shared/Navbar/Search.tsx
  src/components/Shared/Navbar/index.tsx
  src/components/Shared/Pending.tsx
  src/components/Shared/UserProfile.tsx
  src/components/utils/matchers/MentionMatcher.tsx
  src/pages/404.tsx
  src/pages/500.tsx
Labels: 💅 enhancement

#560 fix: add auto pausing video when video player leaves viewport
  src/components/Shared/Video.tsx
Labels: 🐛 bug

#561 chore: add apollo state update for likes
  src/components/Publication/Actions/Like.tsx
Labels: 💅 enhancement

#565 feat: add mvp staff tools page
  src/components/Profile/Details.tsx
  src/components/Publication/index.tsx
  src/components/Shared/Navbar/StaffBar.tsx
  src/components/StaffTools/Panels/MetaDetails.tsx
  src/components/StaffTools/Panels/Profile.tsx
  src/components/StaffTools/Panels/Publication.tsx
  src/components/StaffTools/Sidebar.tsx
  src/components/StaffTools/Stats/index.tsx
  src/pages/stafftools/index.tsx
Labels: ✨ feature

#567 feat: move stats to staff page
  src/components/Shared/Navbar/StaffBar.tsx
  src/components/Shared/Navbar/Stats.tsx
  src/components/StaffTools/Stats/index.tsx
Labels: 💅 enhancement
