Repository heyverse/hey, pull requests merged in 2022-10, with the labels that each got.

#710 deprecate: crowdfund feature
  src/components/Comment/Feed.tsx
  src/components/Crowdfund/New.tsx
  src/components/Explore/Feed.tsx
  src/components/Home/Feed.tsx
  src/components/Mod/Feed.tsx
  src/components/Notification/List.tsx
  src/components/Notification/Type/CollectNotification/Amount.tsx
  src/components/Notification/Type/CollectNotification/Content.tsx
  src/components/Notification/Type/CollectNotification/index.tsx
  src/components/Notification/Type/MirrorNotification.tsx
  src/components/Profile/Feed.tsx
  src/components/Profile/Following.tsx
  src/components/Profile/MutualFollowers/List.tsx
  src/components/Profile/NFTFeed.tsx
  src/components/Publication/Actions/index.tsx
  src/components/Publication/Crowdfund/Fund.tsx
  src/components/Publication/Crowdfund/index.tsx
  src/components/Publication/PublicationBody.tsx
  src/components/Publication/SinglePublication.tsx
  src/components/Publication/ThreadBody.tsx
  src/components/Publication/Type/Collected.tsx
  src/components/Publication/Type/Mirrored.tsx
  src/components/Publication/Type/index.tsx
  src/components/Search/Profiles.tsx
  src/components/Search/Publications.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Allowance/Button.tsx
  src/components/Shared/Modal/Collectors.tsx
  src/components/Shared/Modal/Likes.tsx
  src/components/Shared/Modal/Mirrors.tsx
  src/components/Shared/Navbar/MoreNavItems.tsx
  src/components/Shared/Shimmer/CrowdfundShimmer.tsx
  src/components/StaffTools/Stats/index.tsx
  src/generated/documents.ts
  src/graphql/queries/LensterStats.graphql
  src/graphql/queries/Notifications.graphql
  src/pages/new/crowdfund.tsx
  src/tracking.ts
Labels: hacktoberfest-accepted

#712 Expand image, Refresh recommended users, Improve search, Use reflect api
  package.json
  src/components/Settings/Account/CrossPost.tsx
  src/components/Shared/Attachments.tsx
  src/components/Shared/Navbar/MoreNavItems.tsx
  src/styles.css
  yarn.lock
Labels: hacktoberfest-accepted

#716 feat: messages
  data/featureFlags.ts
  src/components/Messages/index.tsx
  src/components/Shared/Navbar/SignedUser.tsx
  src/components/Shared/Navbar/index.tsx
  src/pages/messages.tsx
Labels: ✨ feature

#718 fix: canComment and canMirror in commentOn field
  src/generated/types.ts
  src/graphql/fragments/CommentFields.graphql
  src/graphql/fragments/MirrorFields.graphql
Labels: hacktoberfest-accepted

#724 feat:composer v2
  data/feature-flags.ts
  src/components/Comment/Feed.tsx
  src/components/Composer/Comment/New.tsx
  src/components/Composer/Post/New.tsx
  src/components/Composer/Post/NewPostModal.tsx
  src/components/Composer/PostV2/New.tsx
  src/components/Home/index.tsx
  src/components/Shared/Navbar/index.tsx
Labels: ✨ feature

#727 chore: remove revenue stats
  src/components/StaffTools/Stats/index.tsx
  src/generated/types.ts
  src/graphql/queries/LensterStats.graphql
Labels: 💅 enhancement

#732 fix: reduce dom depth in card component
  src/components/Composer/Comment/New.tsx
  src/components/Composer/Post/Update/index.tsx
  src/components/Home/Announcement.tsx
  src/components/Home/EnableDispatcher.tsx
  src/components/Home/RecommendedProfiles.tsx
  src/components/Home/SetDefaultProfile.tsx
  src/components/Home/SetProfile.tsx
  src/components/Home/Trending.tsx
  src/components/Mod/index.tsx
  src/components/NFT/SingleNFT.tsx
  src/components/Profile/New.tsx
  src/components/Publication/RelevantPeople.tsx
  src/components/Publication/Shimmer.tsx
  src/components/Publication/index.tsx
  src/components/Search/Profiles.tsx
  src/components/Settings/Account/CrossPost.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Account/Verification.tsx
  src/components/Settings/Allowance/Allowance.tsx
  src/components/Settings/Allowance/Module.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Dispatcher/index.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Settings/Profile/index.tsx
  src/components/Shared/CollectWarning.tsx
  src/components/Shared/CommentWarning.tsx
  src/components/Shared/Modal/Report/index.tsx
  src/components/Shared/Shimmer/NFTShimmer.tsx
  src/components/Shared/Shimmer/UserProfilesShimmer.tsx
  src/components/StaffTools/Panels/Profile.tsx
  src/components/StaffTools/Panels/Publication.tsx
  src/components/UI/Card.tsx
  src/lib/getUserLocale.ts
Labels: 💅 enhancement

#733 feat: add message button to profile using xmtp
  data/feature-flags.ts
  data/xmtp-members.ts
  package.json
  src/components/Profile/Details.tsx
  src/components/Profile/Message.tsx
  yarn.lock
Labels: ✨ feature

#743 feat: add core message components and store
  src/components/Messages/index.tsx
  src/components/Messages/message.tsx
  src/components/utils/hooks/useStreamMessages.tsx
  src/pages/messages/[address].tsx
  src/pages/messages/index.tsx
  src/store/message.ts
Labels: ✨ feature

#748 chore: update new post modal
  src/components/Composer/Post/New.tsx
  src/components/Composer/Post/Update/index.tsx
  src/components/UI/MentionTextArea.tsx
  src/styles.css
Labels: 💅 enhancement

#749 refactor: who can comment and mirror
  src/components/Composer/Comment/New.tsx
  src/components/Composer/Post/Update/index.tsx
  src/components/Shared/SelectReferenceModule/index.tsx
  src/store/referencemodule.ts
  src/tracking.ts
Labels: 💅 enhancement

#756 refactor: collect settings
  src/components/Composer/Comment/New.tsx
  src/components/Composer/Post/Update/index.tsx
  src/components/Shared/CollectSettings/CollectForm.tsx
  src/components/Shared/CollectSettings/index.tsx
  src/components/Shared/ReferenceSettings/index.tsx
  src/components/Shared/SelectCollectModule/FeeEntry.tsx
  src/components/Shared/SelectCollectModule/Modules.tsx
  src/lib/getModule.ts
  src/store/collectmodule.ts
Labels: 💅 enhancement

#765 fix: lightbox focus
  src/components/Shared/Attachments.tsx
  src/components/UI/LightBox.tsx
Labels: 🐛 bug

#755 feat: add message list
  src/components/Messages/Message.tsx
  src/components/Messages/index.tsx
  src/components/Shared/MessageComposer.tsx
  src/components/Shared/MessagesList.tsx
  src/components/utils/hooks/useGetMessages.tsx
  src/components/utils/hooks/useSendMessage.tsx
  src/components/utils/hooks/useStreamMessages.tsx
  src/pages/messages/[address].tsx
Labels: ✨ feature

#822 fix: text color and bg of explore tab in dark mode
  src/components/Explore/FeedType.tsx
  src/components/Explore/index.tsx
Labels: 🐛 bug

#828 fix: upload multiple files at ones
  src/components/Shared/Attachment.tsx
  src/lib/uploadMediaToIPFS.ts
Labels: 🐛 bug

#838 chore: remove PAGINATION from leafwatch
  src/components/Comment/Feed.tsx
  src/components/Explore/Feed.tsx
  src/components/Home/Feed.tsx
  src/components/Home/Highlights.tsx
  src/components/Mod/Feed.tsx
  src/components/Notification/List.tsx
  src/components/Profile/Feed.tsx
  src/components/Profile/Followers.tsx
  src/components/Profile/Following.tsx
  src/components/Profile/MutualFollowers/List.tsx
  src/components/Profile/NFTFeed.tsx
  src/components/Search/Profiles.tsx
  src/components/Search/Publications.tsx
  src/components/Shared/Modal/Collectors.tsx
  src/components/Shared/Modal/Likes.tsx
  src/components/Shared/Modal/Mirrors.tsx
  src/tracking.ts
Labels: 💅 enhancement

#839 feat: move to react infinite scroller
  package.json
  src/components/Comment/Feed.tsx
  src/components/Explore/Feed.tsx
  src/components/Home/Feed.tsx
  src/components/Home/Highlights.tsx
  src/components/Mod/Feed.tsx
  src/components/Notification/List.tsx
  src/components/Profile/Feed.tsx
  src/components/Profile/Followers.tsx
  src/components/Profile/Following.tsx
  src/components/Profile/MutualFollowers/List.tsx
  src/components/Profile/NFTFeed.tsx
  src/components/Search/Profiles.tsx
  src/components/Search/Publications.tsx
  src/components/Shared/Modal/Collectors.tsx
  src/components/Shared/Modal/Likes.tsx
  src/components/Shared/Modal/Mirrors.tsx
  src/components/UI/InfiniteLoader.tsx
  src/constants.ts
  yarn.lock
Labels: 🐛 bug, 💅 enhancement

#859 feat: new conversation
  src/components/Messages/PreviewList.tsx
  src/components/Messages/index.tsx
  src/components/Shared/Navbar/Search.tsx
  src/components/Shared/Navbar/index.tsx
  src/components/Shared/UserProfile.tsx
  src/components/utils/hooks/useGetMessages.tsx
  src/components/utils/hooks/useMessagePreviews.tsx
  src/components/utils/hooks/useXmtpClient.tsx
  src/store/message.ts
Labels: ✨ feature

#847 feat: audio upload and audio player
  package.json
  src/components/Composer/Comment/New.tsx
  src/components/Composer/Post/Update/index.tsx
  src/components/Publication/PublicationBody.tsx
  src/components/Publication/QueuedPublication.tsx
  src/components/Shared/Attachment.tsx
  src/components/Shared/Attachments.tsx
  src/components/Shared/Audio/CoverImage.tsx
  src/components/Shared/Audio/index.tsx
  src/components/Shared/ReferenceSettings/index.tsx
  src/components/UI/MentionTextArea.tsx
  src/constants.ts
  src/generated/types.ts
  src/graphql/fragments/MetadataFields.graphql
  src/lib/formatSeconds.ts
  src/lib/getAttributeFromTrait.ts
  src/lib/getThumbnailUrl.ts
  src/store/publication.ts
  yarn.lock
Labels: ✨ feature

#796 feat: timeline v2
  data/aave-members.ts
  data/feature-flags.ts
  src/apollo.ts
  src/components/Home/FeedEventFilters.tsx
  src/components/Home/FeedType.tsx
  src/components/Home/index.tsx
  src/components/Publication/Actions/Collect/CollectModule.tsx
  src/components/Publication/Actions/Collect/index.tsx
  src/components/Publication/Actions/index.tsx
  src/components/Publication/SinglePublication.tsx
  src/components/Shared/ReferralAlert.tsx
  src/components/Timeline/EventType/Collected.tsx
  src/components/Timeline/EventType/Combined.tsx
  src/components/Timeline/EventType/Commented.tsx
  src/components/Timeline/EventType/Mirrored.tsx
  src/components/Timeline/EventType/ProfileCircles.tsx
  src/components/Timeline/EventType/Reacted.tsx
  src/components/Timeline/EventType/index.tsx
  src/components/Timeline/index.tsx
  src/components/UI/Checkbox.tsx
  src/generated/types.ts
  src/graphql/queries/Timeline.graphql
  src/store/timeline.ts
Labels: ✨ feature
