Repository heyverse/hey, pull requests merged in 2022-07, with the labels that each got.

#78 chore: remove vs code setttings
  .vscode/extensions.json
  .vscode/settings.json
Labels: chore

#84 feat: add POH badge
  src/components/Profile/Details.tsx
  src/components/Profile/index.tsx
Labels: feature

#85 chore: add ens badge
  src/components/Profile/Details.tsx
Labels: feature

#92 feat: collect publication without profile 🚀
  src/components/Comment/NewComment/index.tsx
  src/components/Community/Create.tsx
  src/components/Community/Join.tsx
  src/components/Crowdfund/Create.tsx
  src/components/Post/Actions/Collect/CollectModule.tsx
  src/components/Post/Actions/Like.tsx
  src/components/Post/Actions/Mirror.tsx
  src/components/Post/Crowdfund/Fund.tsx
  src/components/Post/NewPost/index.tsx
  src/components/Settings/Account/SetProfile.tsx
  src/components/Settings/Account/SuperFollow.tsx
  src/components/Settings/Delete/index.tsx
  src/components/Settings/Profile/NFTPicture.tsx
  src/components/Settings/Profile/Picture.tsx
  src/components/Settings/Profile/Profile.tsx
  src/components/Shared/Follow.tsx
  src/components/Shared/Navbar/CreateProfile.tsx
  src/components/Shared/Navbar/Login/WalletSelector.tsx
  src/components/Shared/Navbar/MenuItems.tsx
  src/components/Shared/SuperFollow/FollowModule.tsx
  src/components/Shared/Unfollow.tsx
  src/components/SiteLayout.tsx
  src/constants.ts
  src/store/app.ts
Labels: enhancement, feature

#135 feat: add relevant people to pub sidebar
  src/components/Home/RecommendedProfiles.tsx
  src/components/Post/RelevantPeople.tsx
  src/components/Post/Shimmer.tsx
  src/components/Post/index.tsx
Labels: enhancement, feature

#137 Update verified.ts
  data/verified.ts
Labels: documentation

#140 feat: FreeCollectModule by default
  src/constants.ts
  src/lib/getModule.ts
Labels: enhancement

#144 fix: add role attribute to div
  src/components/Post/Actions/index.tsx
Labels: bug

#157 fix: forbidden non-null assertion usage
  src/components/Shared/Attachment.tsx
Labels: bug

#173 feat: Add icon to searchbar
  src/components/Shared/Navbar/Search.tsx
  src/components/UI/Input.tsx
Labels: feature
